export enum VERIFICATION_REQUEST_PERMISSIONS {
  CREATE = 'CREATE_VERIFICATION_REQUESTS',
  FETCH = 'FETCH_VERIFICATION_REQUESTS',
  UPDATE = 'UPDATE_VERIFICATION_REQUESTS',
  DELETE = 'DELETE_VERIFICATION_REQUESTS',
}
